from probcause.tests.test_send_request import test_no_error_query_given, test_no_error_file_given

test_no_error_query_given()

test_no_error_file_given()